name: pure_mixpanel
description: A new pure Dart library for Mixpanel analytics.
version: 1.0.5
author: Nicholas Manning <puremixpanel@gmail.com>
homepage: https://github.com/seenickcode/pure_mixpanel

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5
  http: ^0.12.0
  test: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
